CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Case" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DisplayId" character varying(10) NOT NULL,
    "Name" character varying(90) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Accessed" timestamp with time zone NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Case" PRIMARY KEY ("Id")
);

CREATE TABLE "Organization" (
    "Id" character varying(255) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "DisplayName" character varying(255) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Organization" PRIMARY KEY ("Id")
);

CREATE TABLE "Exhibit" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Reference" text NOT NULL,
    "Description" text NOT NULL,
    "DateTimeSeizedProduced" timestamp with time zone NOT NULL,
    "WhereSeizedProduced" text NOT NULL,
    "SeizedBy" text NOT NULL,
    "CaseId" bigint NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Exhibit" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Exhibit_Case_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Case" ("Id")
);

CREATE TABLE "SharedHash" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ObjectName" character varying(1024) NOT NULL,
    "VersionId" character varying(255) NOT NULL,
    "Md5Hash" character varying(32) NOT NULL,
    "ShaHash" character varying(64) NOT NULL,
    "CaseId" bigint NULL,
    CONSTRAINT "PK_SharedHash" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SharedHash_Case_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Case" ("Id")
);

CREATE TABLE "OrganizationSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" character varying(255) NOT NULL,
    "S3Endpoint" character varying(2083) NOT NULL,
    "S3BucketName" character varying(63) NOT NULL,
    "S3NetworkEncryption" boolean NOT NULL,
    "S3AccessKey" character varying(20) NOT NULL,
    "S3SecretKey" character varying(40) NOT NULL,
    "MeilisearchUrl" character varying(2083) NOT NULL,
    "MeilisearchApiKey" character varying(64) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OrganizationSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganizationSettings_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
);

CREATE TABLE "User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Auth0Id" character varying(255) NOT NULL,
    "JobTitle" character varying(100) NOT NULL,
    "DisplayName" character varying(200) NOT NULL,
    "GivenName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "EmailAddress" character varying(320) NOT NULL,
    "ProfilePicture" character varying(2083) NOT NULL,
    "OrganizationId" character varying(255) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_User_Organization_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organization" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CaseUser" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "IsSIO" boolean NOT NULL,
    "CaseId" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CaseUser" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CaseUser_Case_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Case" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CaseUser_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Event" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp with time zone NOT NULL DEFAULT (now()),
    "Updated" timestamp with time zone NOT NULL DEFAULT (now()),
    "Data" jsonb NOT NULL,
    "EventType" character varying(50) NOT NULL,
    "UserId" bigint NULL,
    CONSTRAINT "PK_Event" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Event_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "Role" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "UserId" bigint NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Role_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "SharedContemporaneousNote" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatorId" bigint NOT NULL,
    "CaseId" bigint NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SharedContemporaneousNote" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SharedContemporaneousNote_Case_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Case" ("Id"),
    CONSTRAINT "FK_SharedContemporaneousNote_User_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SharedTab" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "CreatorId" bigint NOT NULL,
    "CaseId" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SharedTab" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SharedTab_Case_CaseId" FOREIGN KEY ("CaseId") REFERENCES "Case" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SharedTab_User_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "TimeZone" character varying(100) NOT NULL,
    "DateFormat" character varying(50) NOT NULL,
    "TimeFormat" character varying(50) NOT NULL,
    "Locale" character varying(5) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSettings_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContemporaneousNote" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CaseUserId" bigint NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ContemporaneousNote" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContemporaneousNote_CaseUser_CaseUserId" FOREIGN KEY ("CaseUserId") REFERENCES "CaseUser" ("Id")
);

CREATE TABLE "Hash" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ObjectName" character varying(1024) NOT NULL,
    "VersionId" character varying(255) NOT NULL,
    "Md5Hash" character varying(32) NOT NULL,
    "ShaHash" character varying(64) NOT NULL,
    "CaseUserId" bigint NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Hash" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hash_CaseUser_CaseUserId" FOREIGN KEY ("CaseUserId") REFERENCES "CaseUser" ("Id")
);

CREATE TABLE "Tab" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "CaseUserId" bigint NULL,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tab" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tab_CaseUser_CaseUserId" FOREIGN KEY ("CaseUserId") REFERENCES "CaseUser" ("Id")
);

CREATE INDEX "IX_CaseUser_CaseId" ON "CaseUser" ("CaseId");

CREATE INDEX "IX_CaseUser_UserId" ON "CaseUser" ("UserId");

CREATE INDEX "IX_ContemporaneousNote_CaseUserId" ON "ContemporaneousNote" ("CaseUserId");

CREATE INDEX "IX_Event_UserId" ON "Event" ("UserId");

CREATE INDEX "IX_Exhibit_CaseId" ON "Exhibit" ("CaseId");

CREATE INDEX "IX_Hash_CaseUserId" ON "Hash" ("CaseUserId");

CREATE UNIQUE INDEX "IX_OrganizationSettings_OrganizationId" ON "OrganizationSettings" ("OrganizationId");

CREATE INDEX "IX_Role_UserId" ON "Role" ("UserId");

CREATE INDEX "IX_SharedContemporaneousNote_CaseId" ON "SharedContemporaneousNote" ("CaseId");

CREATE INDEX "IX_SharedContemporaneousNote_CreatorId" ON "SharedContemporaneousNote" ("CreatorId");

CREATE INDEX "IX_SharedHash_CaseId" ON "SharedHash" ("CaseId");

CREATE INDEX "IX_SharedTab_CaseId" ON "SharedTab" ("CaseId");

CREATE INDEX "IX_SharedTab_CreatorId" ON "SharedTab" ("CreatorId");

CREATE INDEX "IX_Tab_CaseUserId" ON "Tab" ("CaseUserId");

CREATE INDEX "IX_User_OrganizationId" ON "User" ("OrganizationId");

CREATE UNIQUE INDEX "IX_UserSettings_UserId" ON "UserSettings" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240322111118_Create', '7.0.15');

COMMIT;
